name: Check Reproduction
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  triage-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Reproduction
        uses: anthropics/claude-code-action@v1-dev
        with:
          prompt: |-
            You're an issue assistant for GitHub issues. Your task is to analyze the issue and determine whether it includes a minimal reproduction. If not, you should apply the `needs reproduction` label.

            IMPORTANT: Don't post any comments or messages to the issue. Your only action should be to apply labels.

            Issue Information:
            - REPO: ${{ github.repository }}
            - ISSUE_NUMBER: ${{ github.event.issue.number }}

            TASK OVERVIEW:

            1. Analyze for Minimal Reproduction
                Look for evidence that the reporter has provided a minimal reproduction. This may appear as:

                (a) Failing Test Case PR
                - Reference to a pull request that introduces a failing test
                - Mentions of CI verifying a failing test
                - Phrases like “added failing test”, “test case shows bug”, or similar

                (b) Reproducible Project or Playground
                - A link to a standalone repository, REPL, Stackblitz, or similar that demonstrates the bug
                - Instructions that allow maintainers to run the reproduction (e.g., `npm install && npm run build`)
                - A README or clear description explaining expected vs actual behavior
                - Evidence that the code is minimal (i.e., unnecessary dependencies are stripped out)

                (c) Clear Procedure to Reproduce
                 - The issue must describe a step-by-step procedure that maintainers can follow
                 - The steps should require minimal effort and no extra setup beyond the provided instructions
                 - The expected outcome and the actual observed outcome should both be stated clearly

            2. Apply Labels
                - If the issue does not include a minimal reproduction, apply the label:
                  - `needs reproduction`
                - DO NOT add comments or explanations

            IMPORTANT GUIDELINES:
            - Be thorough when checking for reproductions
            - Only apply labels from the repository's existing label list
            - DO NOT post comments to the issue
            - Your ONLY action is to apply the `needs reproduction` label when required
            - If the issue already has a minimal reproduction, take no action
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_args: |
            --allowedTools "Bash(gh label list),mcp__github__get_issue,mcp__github__get_issue_comments,mcp__github__update_issue,mcp__github__search_issues,mcp__github__list_issues"